#
# Copyright (c) 2020 Intel Corporation.
#
# This work is licensed under the terms of the MIT license.
# For a copy, see <https://opensource.org/licenses/MIT>.
#

float32 cloudiness 0.0
float32 precipitation 0.0
float32 precipitation_deposits 0.0
float32 wind_intensity 0.0
float32 sun_azimuth_angle 0.0
float32 sun_altitude_angle 0.0
float32 fog_density 0.0
float32 fog_distance 0.0
float32 fog_falloff 0.0
float32 wetness 0.0
float32 scattering_intensity 0.0
float32 mie_scattering_scale 0.0
float32 rayleigh_scattering_scale 0.0331
float32 dust_storm 0.0
